### ISSUE TITLE
Test and CI: Sanitizers

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/redGrapes#10]
For this highly concurrent project, the tests should be run with sanitizers in order to spot hard-to-debug bugs early on.

At least [`Address`](https://clang.llvm.org/docs/AddressSanitizer.html) sanitizer, [`Memory`](https://clang.llvm.org/docs/MemorySanitizer.html) sanitizer, [`UndefinedBehaviour`](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) sanitizer, and probably also very helpful [`ControlFlowIntegrity`](https://clang.llvm.org/docs/ControlFlowIntegrity.html) sanitizer should be run (all with Clang; `address`/`memory` is also in GCC).

Contrary from what one knows from valgrind in the past, compiler sanitizers know the actual source code and have an extraordinary low false positive rate in all projects I tested them with so far (e.g. for memory leaks).

For examples, see:

- https://github.com/google/boringssl/blob/master/CMakeLists.txt
- https://github.com/openPMD/openPMD-api/pull/421
- https://github.com/openPMD/openPMD-api/issues/452
- https://github.com/openPMD/openPMD-api/blob/dev/.travis.yml

It's really quite easy, just set `CXXFLAGS="-fsanitize=..."` and `LDFLAGS="-fsanitize=..."` when compiling with clang (`CXX=clang++ CC=clang`) and then run all your tests and examples.

For the case of `address` sanitizer, I also recommend `export ASAN_OPTIONS=detect_stack_use_after_return=1:detect_leaks=1:check_initialization_order=true:strict_init_order=true:detect_stack_use_after_scope=1` before running the tests for deeper inspection.

**Comment by michaelsippel** [comment]
The unit tests now contain the Random-Graph test where execution order is verified by comparing the computation result from an asynchronous run with the result of a sequential run of a randomly generated workload with non-invertible hash operations ( same principle as in [tasklib-benchmark](https://github.com/ComputationalRadiationPhysics/tasklib-benchmark) ).

Another way to verify execution order is to run the cholesky example with different tiling-factors and check the results.
