### ISSUE TITLE
MPI

### ISSUE THREAD

**Issue by michaelsippel** [ComputationalRadiationPhysics/redGrapes#19]
In order to use redGrapes with MPI, there are currently approx. 150 LOC of user code needed for:
* defining task properties for flagging an task as "mpi task"
* a scheduler that uses an exclusive thread for MPI tasks
* managing and polling MPI Requests

(However the first to points are only required if the MPI implementation is not thread safe)

Now the question is: should we include these  already in redGrapes or better don't bloat it with such application specific stuff ?
imho it belongs to the abstraction level like pmacc.

**Comment by ax3l** [comment]
I would suggest to provide and ship stand-alone helper headers that can be included by users but are not pulled by default (to avoid MPI as a fixed dependency).

Things like MPI helpers are definitely general enough that we should ship them. (Philosophy: Batteries included.)

**Comment by michaelsippel** [comment]
The MPI helper and an example is now included.
I also prepared an helper for cuda stream synchronization, which will be included soon, but I need to test that first ;)

**Comment by ax3l** [comment]
Thanks a lot! The MPI example and helpers look great. Looking forward to the CUDA (and maybe Alpaka, etc.) examples. The more the merrier! :+1:
