### ISSUE TITLE
Logging Library?

### ISSUE THREAD

**Issue by michaelsippel** [ComputationalRadiationPhysics/redGrapes#23]
After writing the same printf debug lines too often, I think some basic logging should be included as default, e.g. about which tasks are created, what properties the tasks have and which dependencies are created, which tasks are currently executed, ...
Of course the logging has to be thread-safe. Also it would be nice to enable/disable the logging component wise (e.g. only show task dependencies, not execution)

What do you think, should we use a logging library or is this a dependency too much for such a trivial task? Any recommendations for a good c++ logging library?

**Comment by sbastrakov** [comment]
I really like the idea to use some library for logging, also some time ago we discussed it with @psychocoderHPC  as a possibility for PIConGPU, which now uses its own code for logging.

**Comment by michaelsippel** [comment]
We will use [spdlog](https://github.com/gabime/spdlog)
