### ISSUE TITLE
Pretty Printing

### ISSUE THREAD

**Issue by michaelsippel** [ComputationalRadiationPhysics/redGrapes#24]
Currently Tasks can have a label property, but resources only have IDs. For the pretty printing it would be nice, if resouces could be named too.

**Comment by michaelsippel** [comment]
Currently the pretty printing looks like this. This requires two dependencies: [termcolor](https://github.com/ikalnytskyi/termcolor) and [ostream_indenter](https://github.com/spacemoose/ostream_indenter)


![image](https://user-images.githubusercontent.com/1889801/91643664-c8fd7f00-ea24-11ea-9000-9943389bfd77.png)

**Comment by sbastrakov** [comment]
I like it!

**Comment by psychocoderHPC** [comment]
> Currently the pretty printing looks like this. This requires two dependencies: [termcolor](https://github.com/ikalnytskyi/termcolor) and [ostream_indenter](https://github.com/spacemoose/ostream_indenter)
> 
> ![image](https://user-images.githubusercontent.com/1889801/91643664-c8fd7f00-ea24-11ea-9000-9943389bfd77.png)

No problem if those dependencies are optional.

btw. the output looks nice

**Comment by michaelsippel** [comment]
> No problem if those dependencies are optional.

OKay then I will make them optional via pp-`#if`s

**Comment by michaelsippel** [comment]
Since spdlog includes the fmtlib which includes support for terminal colors, we don't need the termcolor dependency

**Comment by michaelsippel** [comment]
During debugging a collection of grep-calls emerged in a shell script. I want try making the formatting json compatible while transitioning from ostream to libfmt. This would make it possible to just use jq or similar tools to inspect a run. Also there is no really good way for doing the indentations correctly, therefore maybe we would be better off by letting some external tool doing the pretty-formatting.

Something like this could be used:
```sh
myProgram 2>&1 | grep -Po 'Content-Type: application/json:\K.*$' | jq
```
and then add your jq-query to get the desired information

**Comment by michaelsippel** [comment]
Now, when the log level is set at least to debug, you can do the following to see the pretty formatted task info along with the other logs:

```sh
myProgram | gawk '{
    if(match($0, /(.*emplace_task )(.*)/, a) != 0)
    {
        gsub(/"/, "\\\"", a[2]);
        print a[1];
        system("echo \""a[2]"\" | jq -C");
    }
    else
    { print }
}'
```

**Comment by michaelsippel** [comment]
There is now a shell script at `share/util.sh`
With that you can do now:
```sh
$ ./myProgram | prettify_log
```
```sh
$ ./myProgram | task_json | jq 'select( .schedulingTags == ["MPI"] )'
```
