### ISSUE TITLE
Set affinity for worker threads

### ISSUE THREAD

**Issue by michaelsippel** [ComputationalRadiationPhysics/redGrapes#26]

**Comment by russellsch** [comment]
I would be interested in this for adding redGrapes to applications that use OpenGL, where the OpenGL calls must always be executed in the same thread.

**Comment by psychocoderHPC** [comment]
> I would be interested in this for adding redGrapes to applications that use OpenGL, where the OpenGL calls must always be executed in the same thread.

@russellsch Is there a requirement for your case that the thread where OpenGL is executed is pinned to a core or a group of cores or is the requirement that all OpenGL calls were executed from the same thread?

For one of our codes where @michaelsippel is working on a prototype for integration of redGrapes we have for CUDA the requirement that all CUDA calls were executed from the same thread. @michaelsippel could you point to an example or code!

**Comment by russellsch** [comment]
While I'm certainly no expert, I believe my use case of OpenGL is very similar to the CUDA use case (executing in same thread), @michaelsippel any examples would be much appreciated!

**Comment by michaelsippel** [comment]
Hi @russellsch , 
I strongly suspect that you want certain OpenGL operations on the same (OS-) thread, not necessarily the same physical core.
(which is what this issue is about, pinning worker threads to physical cores)
This is already possible with RedGrapes, you can look at the [MPI example](https://github.com/ComputationalRadiationPhysics/redGrapes/blob/dev/examples/mpi.cpp). There we create a separate scheduler   that handles all tasks tagged with `SCHED_MPI`.  They are executed by the main-thread through the idle-functor ([L82](https://github.com/ComputationalRadiationPhysics/redGrapes/blob/2be19aefd96b0ff1af61961ca36f30578640020a/examples/mpi.cpp#L82)) whenever the mainthread waits for a task result.
You can do something similar for OpenGL tasks. Maybe you even want to create a separate worker thread for OpenGL tasks. Write me if you need any help with how to use RedGrapes in your application :)
